version: "3.8"

services: 

  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQBus
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: RabbitMQBus

  mongo:
    image: mongo
    container_name: mongoDatabase
    ports:
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db

volumes: 
  mongodbdata:
  rabbitmqdata: